name: read-the-docs
channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - boost-cpp=1.74.0=hc6e9bd1_2
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.16.0=h7979940_1007
  - certifi=2020.12.5=py38h578d9bd_1
  - cfitsio=3.470=hb418390_7
  - curl=7.71.1=he644dc0_8
  - expat=2.2.10=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.5=h516909a_1002
  - gdal=3.2.1=py38hc0b2d6b_1
  - geos=3.8.1=he1b5a44_0
  - geotiff=1.6.0=h5d11630_3
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.66.4=hc4f0c31_2
  - glib-tools=2.66.4=hc4f0c31_2
  - hdf4=4.2.13=h10796ff_1004
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=68.1=h58526e2_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.13.1=hbfbb72e_1002
  - kealib=1.4.14=h0042707_0
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_1
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libdap4=3.20.6=h1d1bd15_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgdal=3.2.1=h52563cd_1
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - libglib=2.66.4=h748fe8e_2
  - libgomp=9.3.0=h2828fa1_18
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h74f7ee3_1012
  - liblapack=3.9.0=7_openblas
  - libnetcdf=4.7.4=nompi_h56d31a8_107
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libopenblas=0.3.12=pthreads_h4812303_1
  - libpng=1.6.37=h21135ba_2
  - libpq=12.3=h255efa7_3
  - libspatialite=5.0.0=heaf302f_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=hdc55705_0
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=h72842e0_3
  - lz4-c=1.9.3=h9c3ff4c_0
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.5=py38h18fd61f_1
  - openjpeg=2.3.1=hf7af979_3
  - openssl=1.1.1i=h7f98852_0
  - pcre=8.44=he1b5a44_0
  - pip=21.0=pyhd8ed1ab_1
  - pixman=0.40.0=h36c2ea0_0
  - poppler=0.89.0=h669c267_1
  - poppler-data=0.4.10=0
  - postgresql=12.3=hc2f5b80_3
  - proj=7.1.1=h966b41f_3
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.8.6=hffdb5ce_5_cpython
  - python_abi=3.8=1_cp38
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py38h578d9bd_3
  - sqlite=3.34.0=h74cdb3f_0
  - tiledb=2.1.6=h91fcb0e_1
  - tk=8.6.10=h21135ba_1
  - tzcode=2021a=h7f98852_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.8=ha95c52a_1
  - pip:
    - alabaster==0.7.12
    - attrs==20.3.0
    - babel==2.9.0
    - chardet==3.0.4
    - docutils==0.16
    - idna==2.8
    - imagesize==1.2.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - loguru==0.5.1
    - markupsafe==1.1.1
    - packaging==20.9
    - pbr==5.5.1
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytz==2020.5
    - pyyaml==5.4.1
    - requests==2.22.0
    - six==1.15.0
    - snowballstemmer==2.1.0
    - sphinx==3.4.3
    - sphinx-click==2.5.0
    - sphinx-copybutton==0.3.1
    - sphinx-rtd-theme==0.5.1
    - sphinx-tabs==2.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - stac-py==0.9.0.post6
    - tqdm==4.48.2
    - urllib3==1.25.11
    - ./stac2odc
